events {}

http {
    upstream security_service { server security:8080; }
    upstream uploader_service { server uploader:8080; }
    upstream minio_service    { server minio:9000; }

    server {
        listen 80;

        # Внутренний эндпоинт для проверки токена
        location = /_auth_check {
            internal;
            proxy_pass http://security_service/v1/token/validation;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Authorization $http_authorization;
        }

        # POST /v1/register -> security POST /v1/user (Анонимно)
        location = /v1/register {
            proxy_pass http://security_service/v1/user;
        }

        # POST /v1/token -> security POST /v1/token (Анонимно)
        location = /v1/token {
            proxy_pass http://security_service/v1/token;
        }

        # GET /v1/user -> security GET /v1/user (С проверкой токена)
        location = /v1/user {
            auth_request /_auth_check;
            proxy_pass http://security_service/v1/user;
        }

        # POST /v1/upload -> uploader POST /v1/upload (С проверкой токена)
        location = /v1/upload {
            auth_request /_auth_check;
            proxy_pass http://uploader_service/v1/upload;
        }

        # GET /images/{image} -> minio GET /images/{image} (С проверкой токена)
        location ~ ^/images/(.*)$ {
            auth_request /_auth_check;
            proxy_set_header Host $http_host;
            proxy_pass http://minio_service/images/$1;
        }
    }
}
